name: chromium
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master 
    - name: Customizable Docker Buildx
      uses: ilteoood/docker_buildx@master
      with:
        tag: latest,bullseye
        imageName: bianzhifu/docker-debian-xfce-nonvc-chromium
        dockerFile: chromium/Dockerfile
        publish: true
        dockerUser: ${{ secrets.DOCKER_USERNAME }}
        dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
